# Generated by Django 4.2.7 on 2025-08-26 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('term_semester', models.CharField(max_length=100)),
                ('coordinator', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveIntegerField()),
                ('instructor', models.CharField(max_length=200)),
                ('total_students', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='uca_app.course')),
            ],
            options={
                'ordering': ['section_number'],
                'unique_together': {('course', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='uca_app.course')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='uca_app.course')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sections', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('num_quizzes', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('num_assignments', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('quiz_weight', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('assignment_weight', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('hw_weight', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('midterm_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('final_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('lab_weight', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='uca_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A (92.5–100%)'), ('A-', 'A- (89.5–<92.5%)'), ('B+', 'B+ (86.5–<89.5%)'), ('B', 'B (82.5–<86.5%)'), ('B-', 'B- (79.5–<82.5%)'), ('C+', 'C+ (76.5–<79.5%)'), ('C', 'C (72.5–<76.5%)'), ('C-', 'C- (69.5–<72.5%)'), ('D', 'D (59.5–<69.5%)'), ('F', 'F (<59.5%)')], max_length=3)),
                ('count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='uca_app.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='uca_app.section')),
            ],
            options={
                'ordering': ['grade'],
                'unique_together': {('course', 'section', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('hw', 'Homework'), ('midterm', 'Midterm'), ('final', 'Final'), ('lab', 'Lab')], max_length=20)),
                ('assessment_number', models.PositiveIntegerField(default=1)),
                ('max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='uca_app.section')),
            ],
            options={
                'ordering': ['assessment_type', 'assessment_number'],
                'unique_together': {('section', 'assessment_type', 'assessment_number')},
            },
        ),
    ]
