# Generated by Django 4.2.7 on 2025-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uca_app', '0003_gradecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereport',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='coursereport',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10),
        ),
    ]
