# Generated by Django 4.2.7 on 2025-09-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uca_app', '0004_coursereport_excel_file_coursereport_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereport',
            name='report_type',
        ),
    ]
