# Generated by Django 4.2.7 on 2025-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uca_app', '0005_remove_coursereport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='average_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
