# Generated by Django 4.2.7 on 2025-09-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uca_app', '0006_alter_assessment_average_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfiguration',
            name='assignment_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseconfiguration',
            name='final_weight',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='courseconfiguration',
            name='hw_weight',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='courseconfiguration',
            name='lab_weight',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='courseconfiguration',
            name='midterm_weight',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='courseconfiguration',
            name='quiz_weight',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
