# Generated by Django 4.2.7 on 2025-09-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uca_app', '0007_alter_courseconfiguration_assignment_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_statistics', models.JSONField(default=dict)),
                ('overall_statistics_graph', models.ImageField(blank=True, null=True, upload_to='analysis_graphs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_data', to='uca_app.course')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
